services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      # - ./client:/app/client
      # - /app/client/node_modules
      - ./exercises:/app/client/public/exercises
    expose:
      - "5173"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myapp.rule=PathPrefix(`/exercises`)"
      - "traefik.http.routers.myapp.entrypoints=web"
      - "traefik.http.services.myapp.loadbalancer.server.port=5173"
    command: ["npm", "run", "start"]
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      # - ./server:/app/server
      # - /app/server/node_modules
      - ./exercises:/app/exercises
    expose:
      - "3000"
    # ports:
    #   - "3000:3000"
    command: ["npm", "run", "start"]

networks:
  proxy:
    external: true