version: '3.8'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
      - ./exercises:/app/client/public/exercises
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev"]
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
      - ./exercises:/app/exercises
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]
