name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: [self-hosted,digitaleee]

    steps:
    - name: Trigger Unified Root Deployment
      run: sudo -u lawrence /home/lawrence/workspace/deploy.sh