name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build containers
        run: docker-compose -f docker-compose.yml build

      - name: Run containers
        run: docker-compose -f docker-compose.yml up -d

      - name: Run client tests
        run: |
          docker-compose exec client npm install
          docker-compose exec client npm test || true

      - name: Run server tests
        run: |
          docker-compose exec server npm install
          docker-compose exec server npm test || true

      - name: Stop containers
        run: docker-compose -f docker-compose.yml down

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_KEY }}
          script: |
            cd /path/to/your/project
            git pull origin main
            docker-compose pull
            docker-compose up -d
